name: Deploy Lambda Function

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Compile TypeScript
      run: npm run build

    - name: Create zip file
      run: |
        # Primero copiamos el index.js de la carpeta lambda
        cp lambda/index.js build/
        
        # Nos movemos a build y creamos el zip
        cd build
        zip -r ../function.zip .
        
        # Volvemos a la raíz y añadimos node_modules
        cd ..
        zip -ur function.zip node_modules/

    - name: Deploy to AWS Lambda
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: 'us-east-2'
        function_name: 'bbog-rlb-dynamo-stream-function'
        function_handler: 'index.handler'
        zip_file: 'function.zip'
        runtime: 'nodejs18.x'
        memory_size: 128