name: Deploy Lambda Function

on:
  push:
    branches:
      - main  # Despliega en cada push a la rama "main"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    # Compilar TypeScript a JavaScript
    - name: Compile TypeScript
      run: npm run build

    # Crear el archivo .zip con el código de la Lambda desde la carpeta dist
    - name: Create zip file
      run: zip -r function.zip node_modules build index.js package.json

    - name: Deploy to AWS Lambda
      uses: appleboy/lambda-action@master
      with:
        function-handler: index.handler
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: 'us-east-2'  # Cambia esto a tu región
        function_name: 'bbog-rlb-dynamo-stream-function'  # Nombre de tu Lambda
        zip_file: 'function.zip'
