name: Deploy Lambda Function

on:
  push:
    branches:
      - main  # Despliega en cada push a la rama "main"

jobs:
  deploy:
    name: Deploy Lambda
    with:
      project-name: 'bbog-rlb-dynamo-stream-function'  # Nombre del proyecto
      function-name: 'bbog-rlb-dynamo-stream-function'  # Nombre de la función Lambda
      aws-region: us-east-2  # Cambia esto a tu región
      node-version: 18.x  # Versión de Node.js
      files-to-compress: 'node_modules build package.json'  # Archivos para empaquetar
      function-handler: build/src/index.handler  # Ruta al handler compilado
      function-memory-size: 128  # Tamaño de memoria para la función
      function-runtime: nodejs18.x  # Runtime de AWS Lambda
      continuous-deployment: true

      secrets:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

